### ISSUE TITLE
Further parametrisation of column names

### ISSUE THREAD

**Issue by ns-rse** [Mesnage-Org/pgfinder#273]
Further to #267 / #269 and as [noted](https://github.com/Mesnage-Org/pgfinder/pull/269#discussion_r1529073806) we can fully parametrise all column names.

The changes required would be converting `pgfinder.input` in `libs/pgfinder/config/columns.yaml` to a dictionary...

```yaml
pgfinder:
  # Columns from files are renamed to these values
  input:
    id: ID
    rt: RT (min)
    charge: Charge
    obs: Obs (Da)
    intensity: Intensity
```

...and in turn getting `pgfinder["input"].values()` in place of `pgfinder["input"]` when these are called/used in `lib/pgfinder/pgio.py`.

We would also need to introduce `pgfinder.delta` to hold the value `Delta (ppm)` which would be referenced in place of the currently hard coded `Delta (ppm)` in a few places (generation of these values and subsequent usage).
